/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package service.poller;
import io.vertx.core.Vertx;
import service.poller.controller.PollingController;
import service.poller.model.MySqlServiceModel;
import service.poller.model.ServiceModel;
import service.poller.web.WebService;

public class App {
    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        ServiceModel model = new MySqlServiceModel("database", 3306, "dev", "root", "secret");
        new PollingController(vertx, model);
        new WebService(vertx, model);
    }
}
