/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.2/userguide/building_java_projects.html
 */

plugins {
    application
}

repositories {
    jcenter()
}

dependencies {
    implementation("junit:junit:4.12")
    testImplementation("junit:junit:4.13")
    implementation("io.vertx:vertx-mysql-client:4.0.2")
    implementation("io.vertx:vertx-web-client:4.0.2")
    implementation("io.vertx:vertx-web:4.0.2")

    implementation("com.google.guava:guava:29.0-jre")
}

application {
    mainClass.set("service.poller.App")
}
